name: dair_cobevt
data_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure"
root_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure/train.json"
validate_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure/val.json"
test_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure/val.json"


# load yaml file
yaml_parser: "load_hetero_params"

# comm_range: 100

# select_kp: true

noise_setting:
  add_noise: False
  args:
    pos_std: 0.2
    rot_std: 0.2
    pos_mean: 0
    rot_mean: 0

train_params:
  batch_size: &batch_size 2
  epoches: 30
  eval_freq: 5
  save_freq: 1
  max_cav: &max_cav 2


# dataset configs: fusion, preprocess, postprocess
fusion:
  core_method: 'LiDARCameraIntermediateFusionDatasetDAIRV3' # 'LiDARCameraIntermediateFusionDatasetDAIR' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset(V2X) supported. 
  args: 
    proj_first: &proj_first false
    clip_pc: false
    # core_method: 'CameraIntermediateFusionDataset' configs
    grid_conf: &grid_conf
      xbound: [-51.2, 51.2, 0.4]   # 限制x方向的范围并划分网格
      ybound: [-51.2, 51.2, 0.4]   # 限制y方向的范围并划分网格
      zbound: [-3, 1, 4.0]   # 限制z方向的范围并划分网格
      ddiscr: [2, 50, 48]
      mode: 'LID'
    data_aug_conf: &data_aug_conf
      resize_lim: [0.7, 0.8]
      final_dim: [360, 480]
      rot_lim: [0, 0] #[-3.6, 3.6]
      H: 600
      W: 800
      rand_flip: False
      bot_pct_lim: [0.0, 0.20]
      cams: ['camera0', 'camera1', 'camera2', 'camera3']
      Ncams: 4

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  f1:
    core_method: 'SpVoxelPreprocessor'
    args:
      voxel_size: &voxel_size1 [0.4, 0.4, 4]
      max_points_per_voxel: 32
      max_voxel_train: 32000
      max_voxel_test: 70000
    # lidar range for each individual cav. Format: xyzxyz minmax
    cav_lidar_range: &cav_lidar [ -51.2, -51.2, -3, 51.2, 51.2, 1 ]
  f2:
    core_method: 'SpVoxelPreprocessor'
    args:
      voxel_size: &voxel_size2 [0.1, 0.1, 0.1]
      max_points_per_voxel: 5
      max_voxel_train: 36000
      max_voxel_test: 70000
    # LiDAR range for each individual CAV
    cav_lidar_range: *cav_lidar
  cav_lidar_range: *cav_lidar
  bev_map_resolution: 0.4


data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 4.5
    w: 2
    h: 1.56
    r: [0, 90]
    feature_stride: 2
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15


# model related
model:
  core_method: point_pillar_cobevt
  args:
    voxel_size: *voxel_size1
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: false

    pillar:
      voxel_size: *voxel_size1
      lidar_range: *cav_lidar
      pillar_vfe:
        use_norm: true
        with_distance: false
        use_absolute_xyz: true
        num_filters: [64]
      point_pillar_scatter:
        num_features: 64


    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
    shrink_header:
      kernal_size: [3]
      stride: [1]
      padding: [1]
      dim: [256]
      input_dim: 384 # 128 * 3

    fax_fusion:
      input_dim: 256
      mlp_dim: 256
      agent_size: *max_cav
      window_size: 4
      dim_head: 32
      drop_out: 0.1
      depth: 3
      mask: true


loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 20]

