name: opv2v_cobevt_hetero_s+p_noproj_scratch
root_dir: '/mnt/data/byzhao/OPV2V/train'
validate_dir: '/mnt/data/byzhao/OPV2V/validate'

wild_setting:
  async: false
  async_overhead: 100
  seed: 20
  loc_err: false
  xyz_std: 0.2
  ryp_std: 0.2
  data_size: 1.06 # Mb!!
  transmission_speed: 27 # Mbps!!
  backbone_delay: 10 # ms

yaml_parser: "load_hetero_params"
train_params:
  batch_size: &batch_size 1
  epoches: &epoches 10
  eval_freq: 5
  save_freq: 1
  max_cav: &max_cav 2

fusion:
  core_method: 'LiDARCameraIntermediateFusionDatasetOPV2V_V3' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args:
    proj_first: false
    grid_conf: &grid_conf
      xbound: [-51.2, 51.2, 0.4]   # 限制x方向的范围并划分网格
      ybound: [-51.2, 51.2, 0.4]   # 限制y方向的范围并划分网格
      zbound: [-10, 10, 20.0]   # 限制z方向的范围并划分网格
      ddiscr: [2, 50, 48]
      mode: 'LID'
    data_aug_conf: &data_aug_conf
      resize_lim: [0.7, 0.8]
      final_dim: [300, 400]
      rot_lim: [0, 0] #[-3.6, 3.6]
      H: 600
      W: 800
      rand_flip: False
      bot_pct_lim: [0.0, 0.20]
      cams: ['camera0', 'camera1', 'camera2', 'camera3']
      Ncams: 4

# preprocess-related
preprocess:
  # Options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  f1:
    core_method: 'SpVoxelPreprocessor'
    args:
      voxel_size: &voxel_size1 [ 0.4, 0.4, 4 ]
      max_points_per_voxel: 32
      max_voxel_train: 32000
      max_voxel_test: 70000
    # LiDAR range for each individual CAV
    cav_lidar_range: &cav_lidar [ -51.2, -51.2, -3, 51.2, 51.2, 1 ]
  f2:
    core_method: 'SpVoxelPreprocessor'
    args:
      voxel_size: &voxel_size2 [0.1, 0.1, 0.1]
      max_points_per_voxel: 5
      max_voxel_train: 36000
      max_voxel_test: 70000
    # LiDAR range for each individual CAV
    cav_lidar_range: *cav_lidar
  cav_lidar_range: *cav_lidar
  bev_map_resolution: 0.4


data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor2' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 4
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: point_pillar_cobevt
  args:
    voxel_size: *voxel_size1
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: false
    device: &device 'cuda'

    proj_backbone_args:
      layer_nums: [3]
      layer_strides: [1]
      num_filters: [64]
      inplanes: 64
    
    feat_proj: False
    align_loss: 'no'

    second:
      batch_size: *batch_size
      voxel_size: *voxel_size2
      lidar_range: *cav_lidar
      mean_vfe:
        feature_points: 4
      backbone_3d:
        num_features_out: 32 # 64/2

      model_freeze: False


    pillar:
      voxel_size: *voxel_size1
      lidar_range: *cav_lidar
      pillar_vfe:
        use_norm: true
        with_distance: false
        use_absolute_xyz: true
        num_filters: [64]
      point_pillar_scatter:
        num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
    shrink_header:
      kernal_size: [3]
      stride: [2]
      padding: [1]
      dim: [256]
      input_dim: 384 # 128 * 3

    fax_fusion:
      input_dim: 256
      mlp_dim: 256
      agent_size: *max_cav
      window_size: 4
      dim_head: 32
      drop_out: 0.1
      depth: 3
      mask: true


      # add decoder later

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.001
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
    core_method: cosineannealwarm #step, multistep, Exponential and cosineannealwarm support
    epoches: *epoches
    warmup_lr: 2e-4
    warmup_epoches: 10
    lr_min: 2e-5
