name: dair_coalign_hetero
data_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure"
root_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure/train.json"
validate_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure/val.json"
test_dir: "/mnt/data/byzhao/DAIR-V2X/cooperative-vehicle-infrastructure/val.json"


yaml_parser: "load_hetero_params"
train_params:
  batch_size: &batch_size 2
  epoches: 15
  eval_freq: 5
  save_freq: 1
  max_cav: &max_cav 2

noise_setting:
  add_noise: false
  args:
    pos_std: 0.2
    rot_std: 0.2
    pos_mean: 0
    rot_mean: 0

input_source: ['lidar']
label_type: 'lidar'

comm_range: 100

# box_align:
#   train_result: "opencood/logs/coalign_precalc/dairv2x/train/stage1_boxes.json"
#   val_result: "opencood/logs/coalign_precalc/dairv2x/val/stage1_boxes.json"
#   test_result: "opencood/logs/coalign_precalc/dairv2x/test/stage1_boxes.json"
#   args:
#     use_uncertainty: true
#     landmark_SE2: true
#     adaptive_landmark: false
#     normalize_uncertainty: false
#     abandon_hard_cases: true
#     drop_hard_boxes: true

fusion:
  core_method: 'LiDARCameraIntermediateFusionDatasetDAIRV3' # 'LiDARCameraIntermediateFusionDatasetDAIR' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset(V2X) supported. 
  args: 
    proj_first: &proj_first false
    clip_pc: false
    # core_method: 'CameraIntermediateFusionDataset' configs
    grid_conf: &grid_conf
      xbound: [-51.2, 51.2, 0.4]   # 限制x方向的范围并划分网格
      ybound: [-51.2, 51.2, 0.4]   # 限制y方向的范围并划分网格
      zbound: [-3, 1, 4.0]   # 限制z方向的范围并划分网格
      ddiscr: [2, 50, 48]
      mode: 'LID'
    data_aug_conf: &data_aug_conf
      resize_lim: [0.7, 0.8]
      final_dim: [360, 480]
      rot_lim: [0, 0] #[-3.6, 3.6]
      H: 600
      W: 800
      rand_flip: False
      bot_pct_lim: [0.0, 0.20]
      cams: ['camera0', 'camera1', 'camera2', 'camera3']
      Ncams: 4


# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  f1:
    core_method: 'SpVoxelPreprocessor'
    args:
      voxel_size: &voxel_size1 [0.4, 0.4, 4]
      max_points_per_voxel: 32
      max_voxel_train: 32000
      max_voxel_test: 70000
    # lidar range for each individual cav. Format: xyzxyz minmax
    cav_lidar_range: &cav_lidar [ -51.2, -51.2, -3, 51.2, 51.2, 1 ]
  f2:
    core_method: 'SpVoxelPreprocessor'
    args:
      voxel_size: &voxel_size2 [0.1, 0.1, 0.1]
      max_points_per_voxel: 5
      max_voxel_train: 36000
      max_voxel_test: 70000
    # LiDAR range for each individual CAV
    cav_lidar_range: *cav_lidar
  cav_lidar_range: *cav_lidar
  bev_map_resolution: 0.4


data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor2' # VoxelPostprocessor, BevPostprocessor supported
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 4.5
    w: 2
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2
    num: &anchor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

# model related
model:
  core_method: point_pillar_baseline_multiscale
  args:
    voxel_size: *voxel_size1
    lidar_range: *cav_lidar
    anchor_number: *anchor_num

    proj_backbone_args:
      layer_nums: [3]
      layer_strides: [1]
      num_filters: [64]
      inplanes: 64
    
    align_loss: 'no'
    proj_base_agent: True
    supervise_ego: True
    back_proj: True
    bfp_loss: 'mfro' # options [mfro|abs|mse|cos]

    multimodal:
      # params for camera branch
      use_camera: True
      device: &device 'cuda'
      img_params:
        grid_conf: *grid_conf
        data_aug_conf: *data_aug_conf
        img_downsample: 8
        bev_dim: 64

      # params for lidar branch
      use_lidar: True
      pc_params:
        voxel_size: *voxel_size1
        lidar_range: *cav_lidar
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters: [64]
        point_pillar_scatter:
          num_features: 64

      model_freeze: True
      model_hypes: 'opencood/hypes_yaml/covqm/dair-v2x/SOTAs+vqm/dair_coalign_vqm.yaml'
      model_path: 'opencood/logs/covqm_SOTAs2multimodal/dair_coalign_vqm_2024_10_07_08_03_15'


    pillar:
      voxel_size: *voxel_size1
      lidar_range: *cav_lidar
      pillar_vfe:
        use_norm: true
        with_distance: false
        use_absolute_xyz: true
        num_filters: [64]
      point_pillar_scatter:
        num_features: 64
      
      model_freeze: True
      model_hypes: 'opencood/hypes_yaml/covqm/dair-v2x/SOTAs/dair_coalign.yaml'
      model_path: 'opencood/logs/covqm_SOTAs_compared/dair_coalign_2024_09_13_01_15_53'


    base_bev_backbone: # backbone will downsample 2x
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]

    fusion_method: att
    att:
      feat_dim: [64, 128, 256]

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3

    dir_args: *dir_args
    

loss:
  core_method: point_pillar_loss_coalign
  args:
    pos_cls_weight: 2.0
    cls:
      type: 'SigmoidFocalLoss'
      alpha: 0.25
      gamma: 2.0
      weight: 2.0
    reg:
      type: 'WeightedSmoothL1Loss'
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: 'WeightedSoftmaxClassificationLoss'
      weight: 0.2
      args: *dir_args

optimizer:
  core_method: Adam
  lr: 0.001
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [5, 10]